---

- name: dynamo policies
  iam_managed_policy:
    policy_name: "{{ application }}-dynamo-{{ item }}"
    policy_description: "{{ item }} access to {{ application }} dynamodb table"
    policy: "{{ lookup('template', 'iam-{{ item }}.json.j2') }}"
    state: present
    region: "{{ region }}"
  loop:
    - ro
    - rw

- name: lambda roles for dynamo
  iam_role:
    name: "{{ application }}-dynamo-{{ item }}"
    managed_policy:
      - "{{ application }}-dynamo-{{ item }}"
    assume_role_policy_document:
      Version: '2012-10-17'
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
  loop:
    - ro
    - rw

- name: create dynamodb table
  dynamodb_table:
    name: "{{ application }}"
    region: "{{ region }}"
    hash_key_name: secret
    hash_key_type: STRING
    read_capacity: 1
    write_capacity: 1
    tags:
      app: "{{ application }}"
    wait_for_active_timeout: 120

- name: enable TTL
  dynamodb_ttl:
    region: "{{ region }}"
    state: enable
    table_name: "{{ application }}"
    attribute_name: expire

